### ISSUE TITLE
10 Failing tests

### ISSUE THREAD

**Issue by javadparvaresh** [twada/stringifier#7]
i just pushed the project and run npm test, but we have 10 failing tests.

```shell
[03:02:24] Starting 'unit'...
[03:02:24] Starting 'clean_bundle'...
[03:02:24] Finished 'clean_bundle' after 4.75 ms
[03:02:24] Starting 'bundle'...
[03:02:24] Starting 'clean_assert_bundle'...
[03:02:24] Finished 'clean_assert_bundle' after 443 μs
[03:02:24] Starting 'assert_bundle'...


  ․․․․․․․․․․․․․․․․․․․․․[03:02:25] Finished 'assert_bundle' after 458 ms
[03:02:25] Starting 'build_deps'...
[03:02:25] Finished 'build_deps' after 35 μs
․․․․․․․․․․․․․․․․․․․․․․․․․․․․[03:02:26] Finished 'bundle' after 1.07 s
[03:02:26] Starting 'test_browser'...
[03:02:26] Starting 'test_amd'...
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  217 passing (1s)
  10 failing

  1) strategies anonymous constructor object:

      AssertionError [ERR_ASSERTION]: 'AnonStudent{name:"mary",age:9,gender:"F"}' == '@Anonymous{name:"mary",age:9,gender:"F"}'
      + expected - actual

      -AnonStudent{name:"mary",age:9,gender:"F"}
      +@Anonymous{name:"mary",age:9,gender:"F"}

      at Context.<anonymous> (test/customization_test.js:99:16)

  2) strategies anonymous constructor alternate name:

      AssertionError [ERR_ASSERTION]: 'AnonStudent{name:"mary",age:9,gender:"F"}' == 'Anon{name:"mary",age:9,gender:"F"}'
      + expected - actual

      -AnonStudent{name:"mary",age:9,gender:"F"}
      +Anon{name:"mary",age:9,gender:"F"}

      at Context.<anonymous> (test/customization_test.js:110:16)

  3) strategies type detection override:

      AssertionError [ERR_ASSERTION]: 'AnonStudent{name:"mary",age:9,gender:"F"}' == 'Student{name:"mary",age:9,gender:"F"}'
      + expected - actual

      -AnonStudent{name:"mary",age:9,gender:"F"}
      +Student{name:"mary",age:9,gender:"F"}

      at Context.<anonymous> (test/customization_test.js:271:16)

  4) stringify non-regular prop nameanonymous constructor:

      AssertionError [ERR_ASSERTION]: 'Object{"^pr\\"op-na:me":#AnonPerson#}' == 'Object{"^pr\\"op-na:me":#@Anonymous#}'
      + expected - actual

      -Object{"^pr\"op-na:me":#AnonPerson#}
      +Object{"^pr\"op-na:me":#@Anonymous#}

      at Context.<anonymous> (test/various_types_test.js:211:24)

  5) stringify without maxDepth option single anonymous constructor:

      AssertionError [ERR_ASSERTION]: 'AnonPerson{name:"bob",age:4}' == '@Anonymous{name:"bob",age:4}'
      + expected - actual

      -AnonPerson{name:"bob",age:4}
      +@Anonymous{name:"bob",age:4}

      at Context.<anonymous> (test/various_types_test.js:178:28)

  6) stringify without maxDepth option Array containing anonymous constructor:

      AssertionError [ERR_ASSERTION]: '[AnonPerson{name:"bob",age:4}]' == '[@Anonymous{name:"bob",age:4}]'
      + expected - actual

      -[AnonPerson{name:"bob",age:4}]
      +[@Anonymous{name:"bob",age:4}]

      at Context.<anonymous> (test/various_types_test.js:183:28)

  7) stringify without maxDepth option Object containing anonymous constructor:

      AssertionError [ERR_ASSERTION]: 'Object{val:AnonPerson{name:"bob",age:4}}' == 'Object{val:@Anonymous{name:"bob",age:4}}'
      + expected - actual

      -Object{val:AnonPerson{name:"bob",age:4}}
      +Object{val:@Anonymous{name:"bob",age:4}}

      at Context.<anonymous> (test/various_types_test.js:188:28)

  8) stringify with maxDepth = 1 single anonymous constructor:

      AssertionError [ERR_ASSERTION]: 'AnonPerson{name:"bob",age:4}' == '@Anonymous{name:"bob",age:4}'
      + expected - actual

      -AnonPerson{name:"bob",age:4}
      +@Anonymous{name:"bob",age:4}

      at Context.<anonymous> (test/various_types_test.js:194:28)

  9) stringify with maxDepth = 1 Array containing anonymous constructor:

      AssertionError [ERR_ASSERTION]: '[#AnonPerson#]' == '[#@Anonymous#]'
      + expected - actual

      -[#AnonPerson#]
      +[#@Anonymous#]

      at Context.<anonymous> (test/various_types_test.js:199:28)

  10) stringify with maxDepth = 1 Object containing anonymous constructor:

      AssertionError [ERR_ASSERTION]: 'Object{val:#AnonPerson#}' == 'Object{val:#@Anonymous#}'
      + expected - actual

      -Object{val:#AnonPerson#}
      +Object{val:#@Anonymous#}

      at Context.<anonymous> (test/various_types_test.js:204:28)
```

**Comment by twada** [comment]
@javadparvaresh Thank you for reporting this and nice catch!
Tests are failing since V8 changes (improves) anonymous constructor detection logic.
I'll fix them.

**Comment by twada** [comment]
Now fixed. Thank you for reporting!
